#!/usr/bin/env bash
# This script transfers a file from a client to a server.

if [ $# -lt 1 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i ~/.ssh/school "$1" ubuntu@100.26.18.110:~
fi
