#!/usr/bin/env bash
# Displays fizz-buzz script in numbers from 1 to 10.

for myNumber in {1..100}
do
  if (( myNumber % 3 == 0 && myNumber % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( myNumber % 5 == 0 ))
  then
    echo "Buzz"
  elif (( myNumber % 3 == 0 ))
  then
    echo "Fizz"
  else
    echo "$myNumber"
  fi
done
