#!/usr/bin/env bash
# Show the contents of `/etc/passwd`.
# Only displays the username, id, and home directory path.

while read -r pwdLine; do
  echo "$pwdLine" | cut -d ':' -f1,3,6
done < "/etc/passwd"
