#!/usr/bin/env bash
# Tells a story from contents of the `/etc/passwd` file.

while IFS=':' read -r f1_name f2_pwd f3_uid f4_gid f5_info f6_home f7_shell; do
  echo "The user $f1_name is part of the $f4_gid gang, lives in $f6_home and rides $f7_shell $f3_uid's place is protected by the passcode $f2_pwd, more info about the user here: $f5_info"
done < "/etc/passwd"
