#!/usr/bin/env bash
# Use while loop with case statement.

idx=0

while [ $idx -lt 20 ]
do
	(( idx++ ))
	case $idx in
		"5") echo "bad luck from China";;
		"10") echo "bad luck from Japan";;
		"18") echo "bad luck from Italy";;
	esac
	echo "$idx"
done
